# CI workflow triggered when a PR is added to the merge queue.
#
# The jobs in this workflow are intentionally prefixed with `merge_group`,
# indicating that they need to succeed for a PR to be merged.
# These `merge_group` jobs should also be added in the 'Status checks that are required'
# settings of the Github repository by the maintainer 
# to ensure the job status is checked before merging.
name: Merge Group CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  check_changed_files:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.echo_results.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Check Whether VERSION Changes
        id: changed-version
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true 
          files: VERSION

      - name: Echo Results
        id: echo_results
        env:
          VERSION_CHANGED: ${{ steps.changed-version.outputs.any_changed }}
        run: |
          echo "VERSION changed: $VERSION_CHANGED"
          echo "version_changed=$VERSION_CHANGED" >> "$GITHUB_OUTPUT"
  
  echo_positive:
    needs: check_changed_files
    runs-on: ubuntu-latest
    if: needs.check_changed_files.outputs.version_changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - run: echo "VERSION has changed"

  echo_negative:
    needs: check_changed_files
    runs-on: ubuntu-latest
    if: needs.check_changed_files.outputs.version_changed != 'true'
    steps:
      - uses: actions/checkout@v4

      - run: echo "VERSION does not change"

  # Jobs that will run when VERSION does _not_ change
  merge_group_kernel_test:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/test_asterinas.yml

  merge_group_osdk_test:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/test_osdk.yml
  
  merge_group_check_publish_osdk:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/publish_osdk.yml
    with:
      publish: false

  merge_group_check_build_website:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/publish_website.yml
    with:
      deploy: false

  # Jobs that will run when VERSION changes
  merge_group_docker_push:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed == 'true'
    uses: ./.github/workflows/publish_docker_images.yml
    with:
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  merge_group_kernel_test_new_release:
    needs: [merge_group_docker_push]
    uses: ./.github/workflows/test_asterinas.yml

  merge_group_osdk_test_new_release:
    needs: [merge_group_docker_push]
    uses: ./.github/workflows/test_osdk.yml

  merge_group_check_publish_osdk_new_release:
    needs: [merge_group_docker_push]
    uses: ./.github/workflows/publish_osdk.yml
    with:
      publish: false

  merge_group_check_build_website_new_release:
    needs: [merge_group_docker_push]
    uses: ./.github/workflows/publish_website.yml
    with:
      deploy: false
  
  
