name: Publish OSDK

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to upload doc to online website'
        required: true
        type: 'boolean'
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: false
  workflow_dispatch:

jobs:
  osdk-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: asterinas/asterinas:0.6.2
    steps:
      - uses: actions/checkout@v4

      - name: Check Publish
        # On pull request, set `--dry-run` to check whether OSDK can publish
        if: ${{ !inputs.publish }}
        run: |
          cd osdk
          cargo publish --dry-run
        
      - name: Publish
        # On push, OSDK will be published
        if: ${{ inputs.publish }}
        env:
          REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd osdk
          cargo publish --token ${REGISTRY_TOKEN}
