name: Update API docs

on:
  # Scheduled events for nightly API docs
  schedule:
    # UTC 00:00 everyday
    - cron: "0 0 * * *"
  # Events 
  workflow_call:
    inputs:
      upload:
        description: 'Whether to upload doc to online website'
        required: true
        type: boolean
    secrets:
      API_DOCS_PUBLISH_KEY:
        required: false

  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: asterinas/asterinas:0.2.0

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'asterinas/asterinas'
          path: 'asterinas'

      - name: Check Doc Build
        if: github.event_name != 'schedule' && !inputs.upload
        run: |
          cd asterinas
          make install_osdk
          cd ostd
          cargo osdk doc

      - name: Build & Upload Nightly API Docs
        if: github.event_name == 'schedule'
        env:
          API_DOCS_NIGHTLY_PUBLISH_KEY: ${{ secrets.API_DOCS_NIGHTLY_PUBLISH_KEY }}
        run: |
          KEY_FILE=./api_docs_nightly_publish_key
          echo "$API_DOCS_NIGHTLY_PUBLISH_KEY\n" > ${KEY_FILE}
          bash asterinas/tools/github_workflows/build_and_upload_api_docs.sh nightly ${KEY_FILE} 

      - name: Build & Upload Release API Docs
        if: github.event_name != 'schedule' && inputs.upload
        env:
          API_DOCS_PUBLISH_KEY: ${{ secrets.API_DOCS_PUBLISH_KEY }}
        run: |
          KEY_FILE=./api_docs_publish_key
          echo "$API_DOCS_PUBLISH_KEY\n" > ${KEY_FILE}
          bash asterinas/tools/github_workflows/build_and_upload_api_docs.sh release ${KEY_FILE} 
