name: Pull Request CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_changed_files:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.echo_results.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Check Whether VERSION Changes
        id: changed-version
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true 
          files: VERSION

      - name: Echo Results
        id: echo_results
        env:
          VERSION_CHANGED: ${{ steps.changed-version.outputs.any_changed }}
        run: |
          echo "VERSION changed: $VERSION_CHANGED"
          echo "version_changed=$VERSION_CHANGED" >> "$GITHUB_OUTPUT"

  echo_positive:
    needs: check_changed_files
    runs-on: ubuntu-latest
    if: needs.check_changed_files.outputs.version_changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - run: echo "VERSION has changed"

  echo_negative:
    needs: check_changed_files
    runs-on: ubuntu-latest
    if: needs.check_changed_files.outputs.version_changed != 'true'
    steps:
      - uses: actions/checkout@v4

      - run: echo "VERSION does not change"
  
  # Jobs that will be called if version does not changed

  osdk_test:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/test_osdk.yml
  
  kernel_test:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/test_asterinas.yml
  
  check_build_doc:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/publish_api_docs.yml
    with:
      upload: false

  check_publish_osdk:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/publish_osdk.yml
    with:
      publish: false
  
  check_build_website:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed != 'true'
    uses: ./.github/workflows/publish_website.yml
    with:
      deploy: false

  # Jobs that will be called if version changed
  
  docker_build:
    needs: check_changed_files
    if: needs.check_changed_files.outputs.version_changed == 'true'
    uses: ./.github/workflows/publish_docker_images.yml
    with:
      push: false

  # TODO: we should run more check in the newly-built image, 
  # like osdk test and kernel test. 
  # But we can't reuse the current workflows, so new workflow should be added.
