# Jobs that will be run when a pull request is opened 
# and when the pull request is added to the merge queue.

name: Pull Request CI

on:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
  check_changed_files:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.echo_results.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Check Whether VERSION Changes
        id: changed-version
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true 
          files: VERSION

      - name: Echo Results
        id: echo_results
        env:
          VERSION_CHANGED: ${{ steps.changed-version.outputs.any_changed }}
        run: |
          echo "VERSION changed: $VERSION_CHANGED"
          echo "version_changed=$VERSION_CHANGED" >> "$GITHUB_OUTPUT"

  docker_build_and_push:
    needs: [check_changed_files]
    uses: ./.github/workflows/publish_docker_images.yml
    with:
      build: ${{ needs.check_changed_files.outputs.version_changed == 'true' }}
      push: ${{ needs.check_changed_files.outputs.version_changed == 'true' && github.event_name == 'merge_group' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  osdk_test:
    needs: [check_changed_files, docker_build_and_push]
    uses: ./.github/workflows/test_osdk.yml
    with:
      skip: ${{ needs.check_changed_files.outputs.version_changed == 'true' && github.event_name == 'pull_request' }}
  
  kernel_test:
    needs: [check_changed_files, docker_build_and_push]
    uses: ./.github/workflows/test_asterinas.yml
    with:
      skip: ${{ needs.check_changed_files.outputs.version_changed == 'true' && github.event_name == 'pull_request' }}

  check_publish_osdk_and_ostd:
    needs: [check_changed_files, docker_build_and_push]
    uses: ./.github/workflows/publish_osdk_and_ostd.yml
    with:
      skip: ${{ needs.check_changed_files.outputs.version_changed == 'true' && github.event_name == 'pull_request' }}
      publish: false
  
  check_build_website:
    needs: [check_changed_files, docker_build_and_push]
    uses: ./.github/workflows/publish_website.yml
    with:
      skip: ${{ needs.check_changed_files.outputs.version_changed == 'true' && github.event_name == 'pull_request' }}
      deploy: false
