name: Test OSDK

on:
  workflow_call:
    inputs:
      skip: 
        description: 'Whether to skip test'
        required: false
        default: false
        type: 'boolean'
  workflow_dispatch:

jobs:
  osdk-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        # asterinas/asterinas container is the developing container of asterinas,
        # asterinas/osdk container is built with the intructions from Asterinas Book
        container: ['asterinas/asterinas', 'asterinas/osdk']
    container: ${{ format('{0}:0.6.2', matrix.container) }}
    steps:
      - run: echo "Running in ${{ matrix.container }}"

      - uses: actions/checkout@v4

      - name: Lint
        id: lint
        if: ${{ matrix.container == 'asterinas/asterinas' && !inputs.skip }}
        run: make check_osdk

      # Github's actions/checkout@v4 will result in a new user (not root) 
      # and thus not using the Rust environment we set up in the container. 
      # So the RUSTUP_HOME needs to be set here. 
      # This only breaks when we invoke Cargo in the integration test of OSDK 
      # since the OSDK toolchain is not nightly.
      - name: Unit test
        id: unit_test
        if: ${{ !inputs.skip }}
        run: |
          cd osdk
          RUSTUP_HOME=/root/.rustup cargo +stable build
          RUSTUP_HOME=/root/.rustup cargo test
